### ISSUE TITLE
adopt pull-requests fom vis and visjs-timeline

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-network#7]
We should think about how to adopt (old) pull-requests from [vis](https://github.com/almende/vis/pulls?q=is%3Aopen+is%3Apr) and [visjs-network](https://github.com/visjs-community/visjs-network/pulls?q=is%3Apr+is%3Aclosed).

- [x] [almende/vis#4039](https://github.com/almende/vis/pull/4039), [visjs-network/pull/6](https://github.com/visjs-community/visjs-network/pull/6) and [visjs-network/pull/9](https://github.com/visjs-community/visjs-network/pull/9)
- [x] [almende/vis/pull/3963](https://github.com/almende/vis/pull/3963), [visjs-network/pull/20](https://github.com/visjs-community/visjs-network/pull/20)
- [x] [almende/vis#3888](https://github.com/almende/vis/pull/3888), [visjs-network/pull/23](https://github.com/visjs-community/visjs-network/pull/23)
- [x] [almende/vis#4026](https://github.com/almende/vis/pull/4026), [visjs-network/pull/26](https://github.com/visjs-community/visjs-network/pull/26)
- [x] [almende/vis#4027](https://github.com/almende/vis/pull/4027), [visjs-network/pull/29](https://github.com/visjs-community/visjs-network/pull/29)
- [x] [almende/vis#3771](https://github.com/almende/vis/pull/3771),  [visjs-network/pull/34](https://github.com/visjs-community/visjs-network/pull/34)
- [x] [visjs-network/pull/39](https://github.com/visjs-community/visjs-network/pull/39)
- [x] [almende/vis#3657](https://github.com/almende/vis/pull/3657) and [visjs-network/pull/40](https://github.com/visjs-community/visjs-network/pull/40)
- [x] [visjs-network/pull/43](https://github.com/visjs-community/visjs-network/pull/43)
- [x] [visjs-network/pull/45](https://github.com/visjs-community/visjs-network/pull/45)
- [x] [visjs-network/pull/47](https://github.com/visjs-community/visjs-network/pull/47)
- [x] [visjs-network/pull/66](https://github.com/visjs-community/visjs-network/pull/66)
- [x] [visjs-network/pull/68](https://github.com/visjs-community/visjs-network/pull/68)
- [x] [visjs-network/pull/71](https://github.com/visjs-community/visjs-network/pull/71)

Here you can follow the merging progress done in visjs-network: https://github.com/visjs-community/visjs-network/issues/27

Also what would be a good way to provide attribution to the original contributor!?

**Comment by richardeaxon** [comment]
There are a couple of ways to do this (see here https://stackoverflow.com/questions/6022302/how-to-apply-unmerged-upstream-pull-requests-from-other-forks-into-my-fork).

Lets say I want to target almende/vis pull #4280 and merge it into the new vis-network. I could do 

`git pull https://github.com/almende/vis refs/pull/4280/head`

which sucks the entire pull request across but generates masses of merge conflicts due to the structural changes of the new vis-network.

I can also cherry-pick which works just fine for a a single commit like in this pull request. Just wack in the commit ID in almende/vis and git/github figures things out automagically. No merge conflicts and the correct attribution and log messages come across as per the original commit.

`git cherry-pick 9726da595bd1fcb4c5c7264a53fed28f02d69a55`

I am not sure how to handle bigger pulls with multiple commits. Can cherry-pick do that?

**Comment by richardeaxon** [comment]
And from here (https://stackoverflow.com/questions/1670970/how-to-cherry-pick-multiple-commits) you can cherry-pick ranges.

`git cherry-pick 88b1c05abafcd0aa51e89ba417cd4cbc42a2ae60..4c604a38818c96ae252ed2cbd50143f4092a341b`

I did notice that I still had to import the entire remote pull request to load all the refs before I could cherry-pick. So my procedure was:

```
# for a single commit in the pull
git pull https://github.com/almende/vis refs/pull/4280/head
git merge --abort
git cherry-pick 9726da595bd1fcb4c5c7264a53fed28f02d69a55 

# or for a range of commits in a pull
git pull https://github.com/almende/vis refs/pull/4205/head
git merge --abort
git cherry-pick 88b1c05abafcd0aa51e89ba417cd4cbc42a2ae60..4c604a38818c96ae252ed2cbd50143f4092a341b

```
The second example has merge conflicts which would need fixing.

This still requires some manual work and analysis of each pull request to see where it belongs and if it is still valid.

**Comment by mojoaxel** [comment]
@richardeaxon Thanks! Feel free to provide some useful pull-requests :wink:

**Comment by mojoaxel** [comment]
I followed [this](https://coderwall.com/p/sgpksw/git-cherry-pick-from-another-repository) and was successfull. Here is an example:

```
git remote add visjs-network https://github.com/visjs-community/visjs-network.git
git fetch visjs-network
git checkout -b fix-cluster-open-missing-edge-labels
git cherry-pick 89c8ee285a320097b52371e760d6bc41200dbae7
...
```

**Comment by mojoaxel** [comment]
:tada: [vis-timeline@5.1.0](https://github.com/visjs/vis-network/releases/tag/v5.1.0) is now feature-compatible with [visjs-network@4.24.10](https://github.com/visjs-community/visjs-network/tree/3a5d25522cc2fbc2e10f9acef77df1aa0332b440) :rocket:
